apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello
resources:
- service.yaml
- deployment.yaml
images:
- name: hello
  newName: ghcr.io/sunggun-yu/hello-app
  newTag: 0.2.0
