apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: Service1
    service: Service1
    version: V2
  name: hello
  namespace: hello
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
    name: Service1
    service: Service1
    version: V2
  name: hello
  namespace: hello
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
    name: Service1
    service: Service1
    version: V2
  name: hello
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
        name: Service1
        service: Service1
        version: V2
    spec:
      containers:
      - env:
        - name: SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service']
        - name: VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['version']
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: COLOR
          value: '#ef476f'
        image: ghcr.io/sunggun-yu/hello-app:0.6.0
        imagePullPolicy: IfNotPresent
        name: hello
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 20m
            memory: 128Mi
      serviceAccountName: hello
