apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
    name: Service1
    service: Service1
    version: V2
  name: hello
  namespace: hello
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
    name: Service1
    service: Service1
    version: V2
  name: hello
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
        name: Service1
        service: Service1
        version: V2
    spec:
      containers:
      - env:
        - name: SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service']
        - name: VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['version']
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: COLOR
          value: '#ef476f'
        image: hello-app:0.2.1
        imagePullPolicy: Always
        name: hello
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 100m
            memory: 256Mi
