apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: hello
labels:
- pairs:
    name: Service3
    service: Service3
    version: V1
  includeTemplates: true
  includeSelectors: false
