name: release

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: hello-app

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: go

  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      metadata: ${{ steps.goreleaser.outputs.metadata }}
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config --global url."https://bot:${{ steps.app-token.outputs.token }}@github.com/".insteadOf https://github.com/

      - id: goreleaser
        name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean

  update-manifest:
    runs-on: ubuntu-latest
    needs: [release-please, goreleaser]
    if: ${{ needs.release-please.outputs.releases_created }}
    steps:

      - name: Install Kustomization
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/

      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global url."https://${{ steps.app-token.outputs.app-slug }}:${{ steps.app-token.outputs.token }}@github.com/".insteadOf https://github.com/

      - name: Set git identity
        run: |
          git config user.name ${{ steps.app-token.outputs.app-slug }}
          git config user.email ${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com

      - name: Update manifest and push
        run: |
          TAG_NAME=${{ needs.release-please.outputs.tag_name }}
          TAG_NAME=${TAG_NAME#v}
          cd manifests/base
          kustomize edit set image service-provider=$DOCKER_IMAGE_NAME:$TAG_NAME
          cat kustomization.yaml

      - name: Build manifest
        run: |
          kustomize build manifests/base > manifests/install.yaml
          cat manifests/install.yaml

      - name: Push changes
        run: |
          git add manifests
          git commit -m "chore: release manifest for $TAG_NAME"
          git push origin $GITHUB_REF_NAME
